### ISSUE TITLE
Far field intensity plotting

### ISSUE THREAD

**Issue by SchroederSa** [svenreiche/Genesis-1.3-Version4#198]
Hi,

I am simulating a simple individual FEL setup and plotting the pulse energy and far-field intensity profile as described in Example 3. My far-field doesn't look anything like in the example, and I am wondering if I am missing something in the setup of the simulations, e.g. if the simulations lack in resolution or something similar. Do you have an intuition of what the source of such a far-field evolution could  be?

I very much appreciate your help!

<img width="660" alt="Screenshot 2024-09-22 at 1 27 05 PM" src="https://github.com/user-attachments/assets/a31bc3d9-755b-4e00-88c4-e37e6a4e0512">

```
&setup
rootname=explicitbeam
outputdir=DATA/Convergence/
lattice=VISA.lat
beamline=VISA
lambda0=421e-9
gamma0=195.7
delz=0.018
seed=1
nbins=4
npart=16384
shotnoise=1
field_global_stat=true
beam_global_stat=true
write_meta_file=false
exclude_spatial_output=true
exclude_fft_output=true
exclude_current_output=true
exclude_aux_output=true
&end

&time
s0=-50e-6
slen=130e-6
sample=1
&end

&field
power=0
ngrid=561
waist_size=205.18e-6
&end

&profile_gauss
label=current
c0=1193
s0=0
sig=10e-6
&end

&profile_polynom
label=energy
c0=195.7
c1=985000
&end

&beam
gamma=@energy
current=@current
delgam=0.56
ex=5.12e-6
ey=5.12e-6
betax=0.5
betay=0.5
alphax=0
alphay=0
&end

&track
&end

```

```
D: DRIFT = { l = 0.018};
QF: QUADRUPOLE = { l = 0.108, k1= 99.83};
QDa: QUADRUPOLE = { l = 0.108, k1= -99.83};
QFa: QUADRUPOLE = { l = 0.054, k1= 99.83};

QDb: QUADRUPOLE = { l = 0.108, k1= -99.83, dx=0};
QFb: QUADRUPOLE = { l = 0.054, k1= 99.83, dx=0};

QDc: QUADRUPOLE = { l = 0.108, k1= -99.83};
QFc: QUADRUPOLE = { l = 0.054, k1= 99.83};

QDd: QUADRUPOLE = { l = 0.108, k1= -99.83};
QFd: QUADRUPOLE = { l = 0.054, k1= 99.83};

UND: UNDULATOR = {lambdau=0.018000,nwig=14,aw=0.8916};

M: MARKER = {dumpfield = 1, dumpbeam = 1};

FODOa: LINE={UND,QFa@0.000,D@0.054,QDa@0.072,D@0.180,QFa@0.198};
FODOb: LINE={UND,QFb@0.000,D@0.054,QDb@0.072,D@0.180,QFb@0.198};
FODOc: LINE={UND,QFc@0.000,D@0.054,QDc@0.072,D@0.180,QFc@0.198};
FODOd: LINE={UND,QFd@0.000,D@0.054,QDd@0.072,D@0.180,QFd@0.198};

VISA: LINE={M, 4*FODOa,4*FODOb,4*FODOc,4*FODOd};
```

**Comment by svenreiche** [comment]
Hi,
I have looked into your input files.   The parameters are working in steady-state model with saturation within 4 m and quite a good agreement with Ming Xie model. I didn't optimized anything, just used the peak current and the central energy. There is one input parameter, which should be adjusted. It is the grid size, which uses the default value of 1mm. When the radiation is not focused it will hit the grid boundary quickly and then reflected back to the center of the grid. In that context the simulation is more a waveguide mode than a free-space propagation.

In time-dependent simulation there is one major issue and the reason why you haven't seen anything.
The energy chirp over +/-sigma of the current profile is 10% while the FEL bandwidth is (according to Ming Xie) about 2%.
So the effective part which can amplified any given frequency is less than 4 microns!!! Or in other terms after 8 undulator periods (15 cm) the radiation slips into a part of the bunch, which cannot amplify the radiation anymore!
This regime is the so called weak superradiance and is a rather slow amplification process which requires much more than 4 m to reach saturation.

You can check this by taking out the profile for the mean energy. The simulation is then performing quite nicely (albeit not as good as the steady-state), since there is still some slippage effects which causes that the radiation spikes slips out of the beam and then has much less current to amplify it further.

Also the parameter are quite extreme (over 1 kA at 100 MeV). There will be very strong space charge issues in the FEL process, both on the long range scale (larger than one radiation wavelength)  to further enhance the existing chirp, but also on the short scale (pushing the electrons against their one space charge fields).
In principle this can be included in Genesis but it is rather thin ice, since there is not much experiences from users for space charge dominated FEL process.


Best, Sven

PS: Since the issue tab is more about reporting bugs or missing feature, it would be better if such problem as you described, are put in the discussion board.

**Comment by SchroederSa** [comment]
@svenreiche, thank you for your detailed and fast reply! This was indeed very helpful! And my apologies for spamming the issue tab; I was entirely unaware of the discussion tab.

Best
Sarah
