### ISSUE TITLE
undulator module

### ISSUE THREAD

**Issue by rl3418** [svenreiche/Genesis-1.3-Version4#74]
[matching conditions in linear undulator.pdf](https://github.com/svenreiche/Genesis-1.3-Version4/files/10913180/matching.conditions.in.linear.undulator.pdf)
Is the undulator module capable of simulating the weak focusing effect in the horizontal direction as described in this paper? Or is it possible to import the undulator field from RADIA?

**Comment by svenreiche** [comment]
Yes it is possible. These are defined by the roll-off coefficient kx and ky of the undulators in the lattice file.

Since these discussions on how to run Genesis are not issues with the codes I would suggest not to use the 'issue' board of github. For more general discussion there is a discussion tap on the github site.

Best regards,
Sven

-----------------------------------
Paul Scherrer Institut
Sven Reiche
WBBA/315
CH-5232 Villigen PSI

Telefon: +41 56 310 51 19
E-Mail: ***@***.******@***.***>***@***.***>***@***.***>

________________________________
From: rl3418 ***@***.***>
Sent: Tuesday, March 7, 2023 20:20
To: svenreiche/Genesis-1.3-Version4 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [svenreiche/Genesis-1.3-Version4] undulator module (Issue #74)


matching conditions in linear undulator.pdf<https://github.com/svenreiche/Genesis-1.3-Version4/files/10913180/matching.conditions.in.linear.undulator.pdf>
Is the undulator module capable of simulating the weak focusing effect in the horizontal direction as described in this paper? Or is it possible to import the undulator field from RADIA?
